// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"pokedex/pkg/datastore/mgo"
	"pokedex/pkg/pokemon/repository"
	"pokedex/pkg/pokemon/service"
)

// Injectors from wire.go:

func initializeApp(ctx context.Context, dbUri mgo.DbUri, dbName mgo.DbName) (*App, error) {
	client, err := mgo.NewClient(ctx, dbUri)
	if err != nil {
		return nil, err
	}
	database := mgo.NewDatabase(client, dbName)
	pokemonRepository := repository.NewPokemonRepository(database)
	pokemonAddingService := service.NewPokemonAddingService(pokemonRepository)
	app := NewApp(pokemonAddingService)
	return app, nil
}

// wire.go:

type App struct {
	pokemonAddingService service.PokemonAddingService
}

func NewApp(
	pokemonAddingService service.PokemonAddingService,
) *App {
	return &App{
		pokemonAddingService: pokemonAddingService,
	}
}
