// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"pokedex/pkg/app"
	"pokedex/pkg/datastore/mysql"
	"pokedex/pkg/pokemon/repository"
	service2 "pokedex/pkg/pokemon/service"
)

// Injectors from wire.go:

func initializeApp(ctx context.Context, conf *app.Config, dbUri string) (*server, error) {
	db, err := mysql.Connect(ctx, dbUri)
	if err != nil {
		return nil, err
	}
	pokemonRepository := repository.NewPokemonRepository(db)
	pokemonAddingService := service2.NewPokemonAddingService(pokemonRepository)
	pokemonGettingService := service2.NewPokemonGettingService(pokemonRepository)
	pokemonUpdatingService := service2.NewPokemonUpdatingService(pokemonRepository)
	mainService := &service{
		pokemonAddingService:   pokemonAddingService,
		pokemonGettingService:  pokemonGettingService,
		pokemonUpdatingService: pokemonUpdatingService,
	}
	mainServer := NewServer(mainService, conf)
	return mainServer, nil
}

// wire.go:

type service struct {
	pokemonAddingService   service2.PokemonAddingService
	pokemonGettingService  service2.PokemonGettingService
	pokemonUpdatingService service2.PokemonUpdatingService
}
